version: '3.0'

services:

  main:
    container_name: main
    build: ./
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - 5000:3000
    command: npm run start:dev
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .development.env
    ports:
      - 3310:3306
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  mysql:
